version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health.txt || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
